/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string }
export interface MenuItem {
  'id' : bigint,
  'categoryId' : bigint,
  'stockQuantity' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'price' : number,
}
export interface OrderEntry {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : bigint,
  'totalAmount' : number,
  'notes' : string,
  'items' : Array<OrderItem>,
  'orderNumber' : bigint,
}
export interface OrderItem {
  'itemName' : string,
  'quantity' : bigint,
  'unitPrice' : number,
  'menuItemId' : bigint,
}
export type OrderStatus = { 'inprogress' : null } |
  { 'pending' : null } |
  { 'done' : null } |
  { 'paid' : null };
export type PaymentMethod = { 'card' : null } |
  { 'cash' : null };
export interface TopSellingItem {
  'name' : string,
  'totalQuantitySold' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string], bigint>,
  'createMenuItem' : ActorMethod<[string, bigint, number, string], bigint>,
  'createOrder' : ActorMethod<
    [Array<OrderItem>, PaymentMethod, string],
    bigint
  >,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrders' : ActorMethod<[], Array<OrderEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItemsByCategory' : ActorMethod<[bigint], Array<MenuItem>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<OrderEntry>>,
  'getOrdersInTimeRange' : ActorMethod<[bigint, bigint], Array<OrderEntry>>,
  'getTopSellingItems' : ActorMethod<
    [bigint, bigint, bigint],
    Array<TopSellingItem>
  >,
  'getTotalRevenueInTimeRange' : ActorMethod<[bigint, bigint], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleMenuItemAvailability' : ActorMethod<[bigint], undefined>,
  'updateCategory' : ActorMethod<[bigint, string], undefined>,
  'updateMenuItem' : ActorMethod<[MenuItem], undefined>,
  'updateOrderNotes' : ActorMethod<[bigint, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];