/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'menuItemId' : IDL.Nat,
});
export const PaymentMethod = IDL.Variant({
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'inprogress' : IDL.Null,
  'pending' : IDL.Null,
  'done' : IDL.Null,
  'paid' : IDL.Null,
});
export const OrderEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'orderNumber' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TopSellingItem = IDL.Record({
  'name' : IDL.Text,
  'totalQuantitySold' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createMenuItem' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Vec(OrderItem), PaymentMethod, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func(
      [OrderStatus],
      [IDL.Vec(OrderEntry)],
      ['query'],
    ),
  'getOrdersInTimeRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(OrderEntry)],
      ['query'],
    ),
  'getTopSellingItems' : IDL.Func(
      [IDL.Int, IDL.Int, IDL.Nat],
      [IDL.Vec(TopSellingItem)],
      ['query'],
    ),
  'getTotalRevenueInTimeRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Float64],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleMenuItemAvailability' : IDL.Func([IDL.Nat], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateMenuItem' : IDL.Func([MenuItem], [], []),
  'updateOrderNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'menuItemId' : IDL.Nat,
  });
  const PaymentMethod = IDL.Variant({ 'card' : IDL.Null, 'cash' : IDL.Null });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'inprogress' : IDL.Null,
    'pending' : IDL.Null,
    'done' : IDL.Null,
    'paid' : IDL.Null,
  });
  const OrderEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'orderNumber' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TopSellingItem = IDL.Record({
    'name' : IDL.Text,
    'totalQuantitySold' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createMenuItem' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Vec(OrderItem), PaymentMethod, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [IDL.Vec(OrderEntry)],
        ['query'],
      ),
    'getOrdersInTimeRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(OrderEntry)],
        ['query'],
      ),
    'getTopSellingItems' : IDL.Func(
        [IDL.Int, IDL.Int, IDL.Nat],
        [IDL.Vec(TopSellingItem)],
        ['query'],
      ),
    'getTotalRevenueInTimeRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Float64],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleMenuItemAvailability' : IDL.Func([IDL.Nat], [], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateMenuItem' : IDL.Func([MenuItem], [], []),
    'updateOrderNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };