/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MenuItem {
    id: bigint;
    categoryId: bigint;
    stockQuantity: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    price: number;
}
export interface TopSellingItem {
    name: string;
    totalQuantitySold: bigint;
}
export interface OrderItem {
    itemName: string;
    quantity: bigint;
    unitPrice: number;
    menuItemId: bigint;
}
export interface OrderEntry {
    id: bigint;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    createdAt: bigint;
    totalAmount: number;
    notes: string;
    items: Array<OrderItem>;
    orderNumber: bigint;
}
export interface UserProfile {
    name: string;
}
export interface Category {
    id: bigint;
    name: string;
}
export enum OrderStatus {
    inprogress = "inprogress",
    pending = "pending",
    done = "done",
    paid = "paid"
}
export enum PaymentMethod {
    card = "card",
    cash = "cash"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCategory(name: string): Promise<bigint>;
    createMenuItem(name: string, categoryId: bigint, price: number, description: string): Promise<bigint>;
    createOrder(items: Array<OrderItem>, paymentMethod: PaymentMethod, notes: string): Promise<bigint>;
    deleteCategory(categoryId: bigint): Promise<void>;
    deleteMenuItem(menuItemId: bigint): Promise<void>;
    getAllCategories(): Promise<Array<Category>>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAllOrders(): Promise<Array<OrderEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMenuItemsByCategory(categoryId: bigint): Promise<Array<MenuItem>>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<OrderEntry>>;
    getOrdersInTimeRange(startTime: bigint, endTime: bigint): Promise<Array<OrderEntry>>;
    getTopSellingItems(startTime: bigint, endTime: bigint, limit: bigint): Promise<Array<TopSellingItem>>;
    getTotalRevenueInTimeRange(startTime: bigint, endTime: bigint): Promise<number>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleMenuItemAvailability(menuItemId: bigint): Promise<void>;
    updateCategory(categoryId: bigint, name: string): Promise<void>;
    updateMenuItem(menuItem: MenuItem): Promise<void>;
    updateOrderNotes(orderId: bigint, notes: string): Promise<void>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<void>;
}
import type { OrderEntry as _OrderEntry, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCategory(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createMenuItem(arg0: string, arg1: bigint, arg2: number, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMenuItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMenuItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createOrder(arg0: Array<OrderItem>, arg1: PaymentMethod, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, to_candid_PaymentMethod_n3(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, to_candid_PaymentMethod_n3(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async deleteCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteMenuItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async getAllCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<OrderEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItemsByCategory(arg0: bigint): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(arg0);
            return result;
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<OrderEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersInTimeRange(arg0: bigint, arg1: bigint): Promise<Array<OrderEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersInTimeRange(arg0, arg1);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersInTimeRange(arg0, arg1);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopSellingItems(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<TopSellingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopSellingItems(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopSellingItems(arg0, arg1, arg2);
            return result;
        }
    }
    async getTotalRevenueInTimeRange(arg0: bigint, arg1: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalRevenueInTimeRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalRevenueInTimeRange(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleMenuItemAvailability(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleMenuItemAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleMenuItemAvailability(arg0);
            return result;
        }
    }
    async updateCategory(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0);
            return result;
        }
    }
    async updateOrderNotes(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderNotes(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_OrderEntry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderEntry): OrderEntry {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    paymentMethod: _PaymentMethod;
    createdAt: bigint;
    totalAmount: number;
    notes: string;
    items: Array<_OrderItem>;
    orderNumber: bigint;
}): {
    id: bigint;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    createdAt: bigint;
    totalAmount: number;
    notes: string;
    items: Array<OrderItem>;
    orderNumber: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n8(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n10(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        notes: value.notes,
        items: value.items,
        orderNumber: value.orderNumber
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    card: null;
} | {
    cash: null;
}): PaymentMethod {
    return "card" in value ? PaymentMethod.card : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inprogress: null;
} | {
    pending: null;
} | {
    done: null;
} | {
    paid: null;
}): OrderStatus {
    return "inprogress" in value ? OrderStatus.inprogress : "pending" in value ? OrderStatus.pending : "done" in value ? OrderStatus.done : "paid" in value ? OrderStatus.paid : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderEntry>): Array<OrderEntry> {
    return value.map((x)=>from_candid_OrderEntry_n6(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    inprogress: null;
} | {
    pending: null;
} | {
    done: null;
} | {
    paid: null;
} {
    return value == OrderStatus.inprogress ? {
        inprogress: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.done ? {
        done: null
    } : value == OrderStatus.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    card: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.card ? {
        card: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
